### ISSUE TITLE
terraform crash with connection shutdown on large number of  pools

### ISSUE THREAD

**Issue by iahmad-khan** [pulse-vadc/terraform-provider-vtm#11]
```
2019/02/12 14:32:18 [TRACE] root: eval: *terraform.EvalRefresh
2019/02/12 14:32:18 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.wp-kibana: connection is shut down
2019/02/12 14:32:18 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.wp-kibana: connection is shut down
2019/02/12 14:32:18 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.wp-kibana
2019/02/12 14:32:18 [TRACE] root: eval: *terraform.EvalReadState
2019/02/12 14:32:18 [TRACE] root: eval: *terraform.EvalRefresh
2019/02/12 14:32:18 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_persistence.w3-pdb-validate_wwpdb_org_jsessionid: connection is shut down
2019/02/12 14:32:18 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_persistence.w3-pdb-validate_wwpdb_org_jsessionid: connection is shut down
2019/02/12 14:32:18 [TRACE] [walkRefresh] Exiting eval tree: vtm_persistence.w3-pdb-validate_wwpdb_org_jsessionid
2019/02/12 14:32:18 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.w3-ens-r9ywwtvj: connection is shut down
2019/02/12 14:32:18 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.w3-ens-r9ywwtvj: connection is shut down
2019/02/12 14:32:18 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.w3-ens-r9ywwtvj
2019/02/12 14:32:18 [TRACE] dag/walk: upstream errored, not walking "provider.vtm (close)"
2019/02/12 14:32:18 [TRACE] dag/walk: upstream errored, not walking "root"
2019/02/12 14:32:18 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-02-12T14:32:18.978Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2019-02-12T14:32:19.009Z [DEBUG] plugin: plugin process exited: path=/usr/local/terraform/terraform-provider-vtm_v5.2.2



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Job failed: exit code 1
```

Do I need to change something on VTM side?

**Comment by iahmad-khan** [comment]
```


* vtm_pool.systems_public_pool: vtm_pool.systems_public_pool: connection is shut down
panic: Get https://www-lb3:9070/api/tm/5.2/config/active/pools/tc-fg-prod_test?expert_keys=auto_scaling/extraargs: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: 
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: goroutine 11346 [running]:
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: github.com/pulse-vadc/go-vtm/5%!e(MISSING)2.vtmConnector.get(0xc422f56d20, 0x70, 0xc421640f90, 0xc42031d860, 0x7, 0xc42031d870, 0xa, 0x0, 0x0, 0x0, ...)
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: 	/space/jenkins/titan/workspace/_Provider_VTMTFMulti_master-CFQCDFQKOZYHAW2Y7DIJGVB5FPF3CSDSNVM4RVIH6TP7CNHWGNTA/build/src/github.com/pulse-vadc/go-vtm/5.2/virtual_traffic_manager.go:68 +0x2e6
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: github.com/pulse-vadc/go-vtm/5%!e(MISSING)2.VirtualTrafficManager.GetPool(0xc4204d4ea0, 0xc4203cad60, 0xf, 0xd5c6a0, 0xc420254160)
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: 	/space/jenkins/titan/workspace/_Provider_VTMTFMulti_master-CFQCDFQKOZYHAW2Y7DIJGVB5FPF3CSDSNVM4RVIH6TP7CNHWGNTA/build/src/github.com/pulse-vadc/go-vtm/5.2/config_pool.go:21 +0x2e3
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: main.resourcePoolExists(0xc4238e23f0, 0xee6600, 0xc42000cf20, 0xc4238e23f0, 0x0, 0x0)
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: 	/space/jenkins/titan/workspace/_Provider_VTMTFMulti_master-CFQCDFQKOZYHAW2Y7DIJGVB5FPF3CSDSNVM4RVIH6TP7CNHWGNTA/build/src/github.com/pulse-vadc/terraform-provider-vtm/5.2.2/resource_pool.go:1068 +0xcb
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: github.com/pulse-vadc/terraform-provider-vtm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc42021f650, 0xc42009e550, 0xee6600, 0xc42000cf20, 0xc4204bf040, 0x4b8a01, 0xd332c0)
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: 	/space/jenkins/titan/workspace/_Provider_VTMTFMulti_master-CFQCDFQKOZYHAW2Y7DIJGVB5FPF3CSDSNVM4RVIH6TP7CNHWGNTA/build/src/github.com/pulse-vadc/terraform-provider-vtm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:331 +0x31e
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: github.com/pulse-vadc/terraform-provider-vtm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc42029b960, 0xc42009e500, 0xc42009e550, 0xa, 0xc422661500, 0xc422b0eb90)
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: 	/space/jenkins/titan/workspace/_Provider_VTMTFMulti_master-CFQCDFQKOZYHAW2Y7DIJGVB5FPF3CSDSNVM4RVIH6TP7CNHWGNTA/build/src/github.com/pulse-vadc/terraform-provider-vtm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: github.com/pulse-vadc/terraform-provider-vtm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4206911e0, 0xc420601100, 0xc4206011d0, 0x0, 0x0)
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: 	/space/jenkins/titan/workspace/_Provider_VTMTFMulti_master-CFQCDFQKOZYHAW2Y7DIJGVB5FPF3CSDSNVM4RVIH6TP7CNHWGNTA/build/src/github.com/pulse-vadc/terraform-provider-vtm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: reflect.Value.call(0xc42030c720, 0xc420350930, 0x13, 0xeec73e, 0x4, 0xc422b0ef18, 0x3, 0x3, 0xc421492180, 0xc422ed2600, ...)
2019-02-12T14:28:44.020Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: 	/usr/local/go/src/reflect/value.go:447 +0x969
2019-02-12T14:28:44.021Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: reflect.Value.Call(0xc42030c720, 0xc420350930, 0x13, 0xc4200e5f18, 0x3, 0x3, 0x428829, 0x8, 0xc421492700)
2019-02-12T14:28:44.021Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: 	/usr/local/go/src/reflect/value.go:308 +0xa4
2019-02-12T14:28:44.021Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: net/rpc.(*service).call(0xc4203e8000, 0xc420328280, 0xc4203b4050, 0xc4203b4060, 0xc42035ae80, 0xc420558920, 0xd33280, 0xc420601100, 0x16, 0xd332c0, ...)
2019-02-12T14:28:44.021Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
2019-02-12T14:28:44.021Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: created by net/rpc.(*Server).ServeCodec
2019-02-12T14:28:44.021Z [DEBUG] plugin.terraform-provider-vtm_v5.2.2: 	/usr/local/go/src/net/rpc/server.go:480 +0x43a
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.w3-wd-tsc_dev: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.w3-wd-tsc_dev: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.w3-fg-mirrors: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.w3-fg-mirrors: unexpected EOF
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.w3-fg-mirrors
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.w3-cbl-ws_stage: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.w3-cbl-ws_stage: unexpected EOF
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.w3-cbl-ws_stage
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.tc-ena-checklist-editor: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.tc-ena-checklist-editor: unexpected EOF
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.tc-ena-checklist-editor
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.w3-ipr-interpro7_dev: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.w3-ipr-interpro7_dev: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.w3-pdb-em_omero: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.w3-pdb-em_omero: unexpected EOF
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.w3-ipr-interpro7_dev
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.w3-pdb-em_omero
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.tc-rcloud-dev: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.tc-rcloud-dev: unexpected EOF
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.tc-rcloud-dev
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.tc-uni-quickgo-geneproduct_int: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.tc-uni-quickgo-geneproduct_int: unexpected EOF
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.tc-uni-quickgo-geneproduct_int
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalSequence
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalGetProvider
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalReadState
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalRefresh
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalSequence
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalGetProvider
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalReadState
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalRefresh
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.mtbl_bii_test: connection is shut down
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.mtbl_bii_test: connection is shut down
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.mtbl_bii_test
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.tc-spot-webulus_dev: connection is shut down
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.tc-spot-webulus_dev: connection is shut down
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.tc-spot-webulus_dev
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalSequence
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalGetProvider
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalReadState
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalRefresh
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.systems_public_pool: connection is shut down
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.systems_public_pool: connection is shut down
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.systems_public_pool
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.tc-fg-prod_test: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.tc-fg-prod_test: unexpected EOF
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.tc-fg-prod_test
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.w3-wd-tsc_dev
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalSequence
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalGetProvider
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalReadState
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalRefresh
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.wp-uni-pepvep-dev: connection is shut down
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.wp-uni-pepvep-dev: connection is shut down
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalSequence
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalGetProvider
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.wp-uni-pepvep-dev
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalReadState
2019/02/12 14:28:44 [TRACE] root: eval: *terraform.EvalRefresh
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.tc-mi-impc-interest: connection is shut down
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.tc-mi-impc-interest: connection is shut down
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalRefresh, err: vtm_pool.tc-quickgo-services: unexpected EOF
2019/02/12 14:28:44 [ERROR] root: eval: *terraform.EvalSequence, err: vtm_pool.tc-quickgo-services: unexpected EOF
2019/02/12 14:28:44 [TRACE] [walkRefresh] Exiting eval tree: vtm_pool.tc-quickgo-services
```


Is there any batch option supported>?

**Comment by iahmad-khan** [comment]
Same issue on provider version 6.0.0 for vTM 18.2

**Comment by ndavidson-pulse** [comment]
Iahmad-khan if you have a support contract it might be worth opening a support case with Pulse Secure - that way we can securely exchanging configuration and system information.

The provider should be able to handle many hundreds of configuration objects without any issue, I would ask you to check the following things:

- A rough indication of what "large numbers" of pools is, are we talking 30-40 100s or over 1000?
- Make sure the vTM you are configuring has sufficient resources, check the load on the host and make sure that it has at least 2GB of RAM.
- How close are you to the vTM? Is it in a cloud or running as a VM on your local laptop. Is it possible that a middle box is closing the connections early.
- How long do you have to wait before the connections start to time out - the REST API has a keep-alive timeout of 30s by default. You can tweak this via an expert key setting, but the API shouldn't be taking nearly 30s to respond.

**Comment by iahmad-khan** [comment]
Hi,

Yes we have a support contract. There are around 800 pools. All defined in one file. There is no issue If I remove them all and leave just a few of them. The machines are on the same subnet , I am runing terraform in docker as gitlab CI runner.


VTM memory:

```
[root@www ~]# free -mh
             total       used       free     shared    buffers     cached
Mem:           15G       6.2G       9.4G       676M       261M       4.5G
-/+ buffers/cache:       1.4G        14G
Swap:         7.9G         0B       7.9G
```

Avergae latency from runner to VTM:  0.2 milisecond

I am using etcd as state backend. etcd is also running closer to runner. 

For the first time it applied all the pools without issue. but for subsequent runs , it results in that problem. I checked in etcd the state is stored as epxcectd.

Can you try the provider 6.0.0 with 800 pools , and 100 persistence classes , with single node etcd as backend on a test VTM ( 18.2 )

**Comment by ndavidson-pulse** [comment]
Have you tried reducing the parallelism of Terraform? By default it may be making lots of back-end connections and overwhelming the REST API  you could  try using the ```-parallelism=n``` set to a lower number like 2 or 4.

**Comment by ndavidson-pulse** [comment]
Also the CPU usage of zeus.configd whilst terraform is running would be interesting to know. Can you please raise a support request with Pulse Secure - I've asked support to escalate you directly to engineering.

**Comment by ndavidson-pulse** [comment]
@iahmad-khan if you are having trouble raising a support case you can always reach out to me directly via my email which is: <my github username without "-pulse"> at pulsesecure.net

**Comment by iahmad-khan** [comment]
@ndavidson-pulse it seems to work , but unfortunately I changed things both on VTM and on the client side terraform settings , so no idea where was the issue. 

By the way , there are some fields not supported by provider 6.0.0 for vtm-18.2 , so either those fields should have been removed from 18.2 or should be supported by provider 6.0.0 

I noticed this issue because currently I am just pulling the json form of config from vtm , convert it to tf format and then apply.

**Comment by ndavidson-pulse** [comment]
@iahmad-khan could you file a new bug for those properties are missing from terraform? I presume you are grabbing the JSON from the REST API directly, the Terraform client and bindings are effectively generated from the same schema as the REST API so theoretically there should be a 121 correspondence.

**Comment by iahmad-khan** [comment]
Yes, this seems a bug , currently , when generating tf code from json , I exclude those keys.

**Comment by ndavidson-pulse** [comment]
Please open a new issue with the specific keys that are missing.

**Comment by iahmad-khan** [comment]
hi

I am facing the same issue again and its random. It keeps crashing.


The number of connections are: ( paralleisim is 1 )

```
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
249
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
323
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
338
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
338
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
389
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
389
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
389
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
389
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
389

and then it crashes 

[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
15
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
15
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
```

what changes do I need to make on the load balancer?

**Comment by iahmad-khan** [comment]
Looks like it is related to the number of connections:

After increasing it to 1000 in the vtm global config , it suceeded , terraform is making too many connections even with parallelism level of 1

here is the trace from start to finish. ( for successful run )

```
root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
0
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
0
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
0
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
0
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
2
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
42
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
97
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
149
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
172
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
210
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
269
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
334
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
404
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
440
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
509
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
558
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
^[[A605
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
686
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
789
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
845
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
912
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
979
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
1021
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
1096
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
1143
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
1215
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
1290
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
1354
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
1355
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
1355
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
1355
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
0
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
0
```

While thiss is working , a safe way would be to have a configuration option in either terraform or this module to limit the number of parallel connections.

**Comment by ndavidson-pulse** [comment]
Hi @iahmad-khan you're commenting on a closed issue we believe is fixed in the latest release - Before you do anything please make sure you have updated your version of the provider to the latest available and terraform itself to at least 0.12.5.

Remember if you've pinned the version of the provider in your templates you'll need to update it there as well as just downloading the new version of the provider.

**Comment by ndavidson-pulse** [comment]
Specifically VTMTF-134  from the release notes: https://github.com/pulse-vadc/terraform-provider-vtm/blob/VTMTF_19_1/RELEASE_NOTES.txt

**Comment by iahmad-khan** [comment]
But we are using the vtm version 18.2, we had recently updated both the version of terraform and provider. I will check again.

**Comment by iahmad-khan** [comment]
@ndavidson-pulse what is the latest provider version for 18.2? or we need to upgrade the vtm? 

I had just a quick look and for the 18.2 , the latest is 6.0.0

Use terraform-provider-vtm_v6.0.0 for the vTM 18.2 LTS Release

that version we already have.

**Comment by ndavidson-pulse** [comment]
The latest version of VTMTF is 19.1 which includes an updated provider for 18.2, `teraform-provider-vtm_v6.0.1` available form the release page here: https://github.com/pulse-vadc/terraform-provider-vtm/releases/tag/VTMTF_19_1

**Comment by iahmad-khan** [comment]
@ndavidson-pulse great , thanks. I will push the update today and see if it works.

**Comment by iahmad-khan** [comment]
@ndavidson-pulse great , looks like it is breaking some stuff:
```

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.



Error: 
Invalid resource name


  on pools.tf line 7, in resource "vtm_pool" "1000genomes_staging":
   7: resource "vtm_pool" 
"1000genomes_staging"
 {

A name must start with a letter and may contain only letters, digits,
underscores, and dashes.

ERROR: Job failed: exit status 1
```

**Comment by ndavidson-pulse** [comment]
That's probably due to a change in the underlying terraform code, not our provider.

**Comment by ndavidson-pulse** [comment]
Yep - specifically called out in the Terraform 0.12 upgrade guide: https://www.terraform.io/upgrade-guides/0-12.html

**Comment by iahmad-khan** [comment]
Same issue after upgrade , maybe i need to change the TCP connections settings? the upgraded version also makes more than 1500 connections. 

Also before the upgrade everything was working fine , now there is a runtime error:

`Error: Error updating vtm_virtual_server 'www6-ebi_https': The resource provided is invalid ; ssl_server_cert_host_mapping %!s(<nil>)`

There are many ssl cert mappings , it doesnt tell which one is wrong. Before upgrade all of the mapping were fine.

**Comment by iahmad-khan** [comment]
@ndavidson-pulse is there a slack channel to quickly find help on these issues.

**Comment by iahmad-khan** [comment]
@ndavidson-pulse 

Terraform 0.12.6 , provider: 6.01

It crashes as soon as the number of connections it makes tries to jump to 1000 or more:
```


[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
391
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
443
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
488
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
525
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
558
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
600
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
648
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
718
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
794
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
887
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
964
[root@www-lb3 ~]# lsof -ni:9070 -sTCP:ESTABLISHED | wc -l
0
[root@www-lb3 ~]# 
[root@www-lb3 ~]# 
```

after terrafrom client crash and connections drop to 0 on vtm side.

**Comment by iahmad-khan** [comment]
I also tried to increase some tcp connections limits:

```
net.core.somaxconn=4096
net.core.netdev_max_backlog=2000
net.ipv4.tcp_max_syn_backlog=2048
net.ipv4.ip_local_port_range="15000 61000"
net.ipv4.tcp_fin_timeout=30
net.ipv4.tcp_tw_recycle=1
net.ipv4.tcp_tw_reuse=1 
net.ipv4.tcp_challenge_ack_limit = 2000
```

**Comment by ndavidson-pulse** [comment]
@iahmad-khan if you want faster support and you're a paying customer of Pulse Secure, the easiest thing to do is raise a support case via https://support.pulsesecure.net/

**Comment by iahmad-khan** [comment]
I am sure this can't be troubleshooted over phone conversation , is there some support email or slack channel?

**Comment by ndavidson-pulse** [comment]
Actually I've just seen the problem, the vendored sources include the older version of the go-vtm API before the underlying issue was fixed - I'll try and push an update and new build ASAP.

**Comment by iahmad-khan** [comment]
Ok , let me know which binary should i downlod after the fix. thanks.

**Comment by ndavidson-pulse** [comment]
This issue has been assigned an internal bug of VTMTF-136, you can use this issue number to search the release notes.

**Comment by iahmad-khan** [comment]
@ndavidson-pulse do you mean once there is a new release then I will search for that bug number or is there already a release with that bug fixed?

**Comment by iahmad-khan** [comment]
@ndavidson-pulse can we have some quick fix to this , our system is broken.

**Comment by ndavidson-pulse** [comment]
@iahmad-khan we're working on it.

**Comment by iahmad-khan** [comment]
Thanks

**Comment by ndavidson-pulse** [comment]
Fixed by release https://github.com/pulse-vadc/terraform-provider-vtm/releases/tag/VTMTF_19_1_1 - @iahmad-khan you'll want terraform-provider-vtm_v6.0.2

**Comment by ndavidson-pulse** [comment]
Did that fix the problem @iahmad-khan ?
